on:
  push:
    branch:
      2.0.x
  workflow_dispatch:

jobs:
  deploy-eap-action:
    runs-on: ubuntu-latest
    name: Deploy to the test EAP nexus
    steps:
      - uses: actions/checkout@v2
      - uses: xstefank/eap-component-deploy-action@main
        with:
          token: ${{ secrets.EAP_NEXUS_SECRET_PASSPHRASE }}

